### ISSUE TITLE
Fork off into new standalone x-platform project

### ISSUE THREAD

**Issue by fatso83** [knutkj/misc#1]
Heisann, Knut!

This project superficially seemed like an _almost_ perfect fit for something we are doing ATM. As we were thinking out load about how we could keep the markup used in our living styleguide in sync with the partials used in the actual ASP.NET application, I realized that all we needed to do was have some way of generating raw html snippets from partials along with some model data, for instance supplied as json. Coming upon this project seemed like a godsend! 

_But_ we are (almost) all command line junkies on macs, and although we are building an ASP.NET application using Windows VMs, we prefer to be able to do as much as possible no our own machines in a easy, scripted fashion. Also outside of this project. Now, naturally we have access to .NET on Mac through the Mono runtime, and lately through ASP.NET Core, but ... this project is written using PowerShell, [which has quite poor support](https://github.com/Pash-Project/Pash) outside of Windows. I did try my best, as you can see, but it seems to me (a non-Windows native) that `CmdLetBinding` is not supported in the current (alpha) version of Pash:

```
alias nuget='mono ~/bin/nuget.exe'
alias pash='mono ~/dev/Pash/Source/PashConsole/bin/Debug/Pash.exe'

nuget  install Razor.Render.CommandLine
Feeds used:
  https://api.nuget.org/v3/index.json

Attempting to gather dependencies information for package 'Razor.Render.CommandLine.1.0.1' with respect to project '/tmp/razorcli', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Razor.Render.CommandLine.1.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Razor.Render.CommandLine.1.0.1'
Resolved actions to install package 'Razor.Render.CommandLine.1.0.1'
Adding package 'AspNetRazor.Core.2.0.20126.16343' to folder '/tmp/razorcli'
Added package 'AspNetRazor.Core.2.0.20126.16343' to folder '/tmp/razorcli'
Successfully installed 'AspNetRazor.Core 2.0.20126.16343' to /tmp/razorcli
Adding package 'Razor.Render.CommandLine.1.0.1' to folder '/tmp/razorcli'
Added package 'Razor.Render.CommandLine.1.0.1' to folder '/tmp/razorcli'
Successfully installed 'Razor.Render.CommandLine 1.0.1' to /tmp/razorcli

pash
Pash - Copyright (C) Pash Contributors. License: GPL/BSD. See https://github.com/Pash-Project/Pash/

PASH /tmp/razorcli> Razor.Render.CommandLine.1.0.1/Tools/Init.ps1
Parse error at (19:18): Syntax error, expected: ]
>     [CmdLetBinding()]
                    ^
  +CategoryInfo: ParserError: (:) [], ParseException
  +FullyQualifiedErrorId: Parse
```

So ... as running PowerShell turned out to be a dead end, I was thinking of starting on a clean slate with a C# app to
- get rid of the powershell dependency
- be able to specify partial and model file names as arguments
- support an output folder or file output name for the generated markup

It would probably just be a ripoff of your current work, I would assume. Any pointers or input before an old Java programmer tries to cobble together a .NET project from scratch? 

ping teammates @ThomasNordengen, @maqnus and @nygter

**Comment by fatso83** [comment]
OK, [first draft of such a tool](https://github.com/fatso83/razor-cli) in place. Feel free to help out :-)

**Comment by knutkj** [comment]
I see I did this five years ago. I don't remember that much I'm afraid. Great if it can help you get started. This book is the source of my inspiration:

Programming Razor
Tools for Templates in ASP.NET MVC or WebMatrix
http://shop.oreilly.com/product/0636920020622.do
